import type { TalentNode } from "../talentTreeRegistry";

// ─── AEGIS TALENT TREE ──────────────────────────────────────
//
// 20 talents | 2 specs: Warrior + Sentinel
//
// Warrior:
//   Melee tank pressure, threat generation, mitigation,
//   counter-attacks, and taunt-style control.
//
// Sentinel:
//   Shields, damage redirection, party-protection,
//   defensive auras, and guardian-style support.
//
// Core Aegis:
//   Shared DEF/HP pressure that supports both tank builds.
//
// IMPORTANT:
// Do not move node positions. The layout spacing is already good.
// ────────────────────────────────────────────────────────────

export const AEGIS_NODES: TalentNode[] = [
  {
    id: "aegis-root",
    tree: "aegis",
    branch: "merge",
    shape: "square",
    name: "Aegis Stance",
    description: "+3% DEF per rank. Core Aegis durability. Unlocks the tree.",
    tradeoff: null,
    maxRank: 4,
    costPerRank: 1,
    requiredLevel: 1,
    requires: [],
    position: { x: 50, y: 11 },
    effects: [{ type: "defense_percent", value: 3 }],
  },
  {
    id: "aegis-warrior-guarded-strike",
    tree: "aegis",
    branch: "warrior",
    shape: "circle",
    name: "Guarded Strike",
    description: "+2% ATK and +2% DEF per rank.",
    tradeoff: null,
    maxRank: 3,
    costPerRank: 1,
    requiredLevel: 2,
    requires: ["aegis-root"],
    position: { x: 20, y: 25 },
    effects: [
      { type: "attack_percent", value: 2 },
      { type: "defense_percent", value: 2 },
    ],
  },
  {
    id: "aegis-sentinel-shield-bloom",
    tree: "aegis",
    branch: "sentinel",
    shape: "circle",
    name: "Shield Bloom",
    description: "+4% shield value per rank.",
    tradeoff: null,
    maxRank: 3,
    costPerRank: 1,
    requiredLevel: 2,
    requires: ["aegis-root"],
    position: { x: 80, y: 25 },
    effects: [{ type: "shield_value", value: 4 }],
  },
  {
    id: "aegis-core-iron-hide",
    tree: "aegis",
    branch: "merge",
    shape: "circle",
    name: "Iron Hide",
    description: "+3% HP per rank.",
    tradeoff: null,
    maxRank: 3,
    costPerRank: 1,
    requiredLevel: 3,
    requires: ["aegis-root"],
    position: { x: 50, y: 25 },
    effects: [{ type: "hp_percent", value: 3 }],
  },
  {
    id: "aegis-warrior-threatening-presence",
    tree: "aegis",
    branch: "warrior",
    shape: "circle",
    name: "Threatening Presence",
    description: "+5% threat generation per rank.",
    tradeoff: null,
    maxRank: 3,
    costPerRank: 1,
    requiredLevel: 3,
    requires: ["aegis-warrior-guarded-strike"],
    position: { x: 10, y: 39 },
    effects: [{ type: "threat_generation", value: 5 }],
  },
  {
    id: "aegis-warrior-counter-guard",
    tree: "aegis",
    branch: "warrior",
    shape: "circle",
    name: "Counter Guard",
    description: "+3% reflect damage per rank after blocking or guarding.",
    tradeoff: "-1% speed per rank.",
    maxRank: 3,
    costPerRank: 1,
    requiredLevel: 3,
    requires: ["aegis-warrior-guarded-strike"],
    position: { x: 30, y: 39 },
    effects: [
      { type: "reflect_damage", value: 3 },
      { type: "speed_percent", value: -1 },
    ],
  },
  {
    id: "aegis-sentinel-warding-light",
    tree: "aegis",
    branch: "sentinel",
    shape: "circle",
    name: "Warding Light",
    description: "+3% damage reduction per rank while shielded.",
    tradeoff: null,
    maxRank: 3,
    costPerRank: 1,
    requiredLevel: 3,
    requires: ["aegis-sentinel-shield-bloom"],
    position: { x: 70, y: 39 },
    effects: [{ type: "damage_reduction", value: 3 }],
  },
  {
    id: "aegis-sentinel-guardian-aura",
    tree: "aegis",
    branch: "sentinel",
    shape: "circle",
    name: "Guardian Aura",
    description: "+2% party defense aura per rank.",
    tradeoff: null,
    maxRank: 3,
    costPerRank: 1,
    requiredLevel: 3,
    requires: ["aegis-sentinel-shield-bloom"],
    position: { x: 90, y: 39 },
    effects: [{ type: "party_defense_aura", value: 2 }],
  },
  {
    id: "aegis-core-stalwart-heart",
    tree: "aegis",
    branch: "merge",
    shape: "circle",
    name: "Stalwart Heart",
    description: "+2% DEF and +2% HP per rank.",
    tradeoff: null,
    maxRank: 3,
    costPerRank: 1,
    requiredLevel: 5,
    requires: ["aegis-core-iron-hide"],
    position: { x: 50, y: 39 },
    effects: [
      { type: "defense_percent", value: 2 },
      { type: "hp_percent", value: 2 },
    ],
  },
  {
    id: "aegis-warrior-taunting-roar",
    tree: "aegis",
    branch: "warrior",
    shape: "triangle",
    name: "Taunting Roar",
    description: "+6% taunt chance per rank.",
    tradeoff: null,
    maxRank: 3,
    costPerRank: 2,
    requiredLevel: 5,
    requires: ["aegis-warrior-threatening-presence"],
    position: { x: 20, y: 53 },
    effects: [{ type: "taunt_chance", value: 6 }],
  },
  {
    id: "aegis-warrior-plate-breaker",
    tree: "aegis",
    branch: "warrior",
    shape: "triangle",
    name: "Plate Breaker",
    description: "+4% counter-attack damage per rank.",
    tradeoff: "-2% mana per rank.",
    maxRank: 3,
    costPerRank: 2,
    requiredLevel: 5,
    requires: ["aegis-warrior-counter-guard"],
    position: { x: 15, y: 65 },
    effects: [
      { type: "counter_attack_damage", value: 4 },
      { type: "mana_percent", value: -2 },
    ],
  },
  {
    id: "aegis-sentinel-shared-burden",
    tree: "aegis",
    branch: "sentinel",
    shape: "triangle",
    name: "Shared Burden",
    description: "+4% damage redirection per rank.",
    tradeoff: "-1% ATK per rank.",
    maxRank: 3,
    costPerRank: 2,
    requiredLevel: 5,
    requires: ["aegis-sentinel-warding-light"],
    position: { x: 60, y: 65 },
    effects: [
      { type: "damage_redirect", value: 4 },
      { type: "attack_percent", value: -1 },
    ],
  },
  {
    id: "aegis-sentinel-sheltering-ward",
    tree: "aegis",
    branch: "sentinel",
    shape: "triangle",
    name: "Sheltering Ward",
    description: "+5% party shield value per rank.",
    tradeoff: null,
    maxRank: 3,
    costPerRank: 2,
    requiredLevel: 5,
    requires: ["aegis-sentinel-guardian-aura"],
    position: { x: 80, y: 53 },
    effects: [{ type: "party_shield_value", value: 5 }],
  },
  {
    id: "aegis-core-unbroken-line",
    tree: "aegis",
    branch: "merge",
    shape: "square",
    name: "Unbroken Line",
    description: "+3% damage reduction per rank.",
    tradeoff: "-1% speed per rank.",
    maxRank: 3,
    costPerRank: 2,
    requiredLevel: 7,
    requires: ["aegis-core-stalwart-heart"],
    position: { x: 50, y: 53 },
    effects: [
      { type: "damage_reduction", value: 3 },
      { type: "speed_percent", value: -1 },
    ],
  },
  {
    id: "aegis-warrior-retaliation",
    tree: "aegis",
    branch: "warrior",
    shape: "triangle",
    name: "Retaliation",
    description: "+5% reflect damage and +3% threat generation per rank.",
    tradeoff: null,
    maxRank: 2,
    costPerRank: 2,
    requiredLevel: 7,
    requires: ["aegis-warrior-taunting-roar", "aegis-warrior-plate-breaker"],
    position: { x: 40, y: 65 },
    effects: [
      { type: "reflect_damage", value: 5 },
      { type: "threat_generation", value: 3 },
    ],
  },
  {
    id: "aegis-sentinel-rallying-barrier",
    tree: "aegis",
    branch: "sentinel",
    shape: "triangle",
    name: "Rallying Barrier",
    description: "+5% shield value and +2% party defense aura per rank.",
    tradeoff: null,
    maxRank: 2,
    costPerRank: 2,
    requiredLevel: 7,
    requires: [
      "aegis-sentinel-shared-burden",
      "aegis-sentinel-sheltering-ward",
    ],
    position: { x: 85, y: 65 },
    effects: [
      { type: "shield_value", value: 5 },
      { type: "party_defense_aura", value: 2 },
    ],
  },
  {
    id: "aegis-warrior-iron-vanguard",
    tree: "aegis",
    branch: "warrior",
    shape: "square",
    name: "Iron Vanguard",
    description: "+8% taunt chance and +6% counter-attack damage.",
    tradeoff: "-3% MAGI.",
    maxRank: 1,
    costPerRank: 3,
    requiredLevel: 9,
    requires: ["aegis-warrior-retaliation"],
    position: { x: 35, y: 79 },
    effects: [
      { type: "taunt_chance", value: 8 },
      { type: "counter_attack_damage", value: 6 },
      { type: "magi_percent", value: -3 },
    ],
  },
  {
    id: "aegis-sentinel-living-fortress",
    tree: "aegis",
    branch: "sentinel",
    shape: "square",
    name: "Living Fortress",
    description: "+8% party shield value and +5% damage redirection.",
    tradeoff: "-3% ATK.",
    maxRank: 1,
    costPerRank: 3,
    requiredLevel: 9,
    requires: ["aegis-sentinel-rallying-barrier"],
    position: { x: 65, y: 79 },
    effects: [
      { type: "party_shield_value", value: 8 },
      { type: "damage_redirect", value: 5 },
      { type: "attack_percent", value: -3 },
    ],
  },
  {
    id: "aegis-core-last-stand",
    tree: "aegis",
    branch: "merge",
    shape: "square",
    name: "Last Stand",
    description: "+6% HP and +4% DEF when below half health.",
    tradeoff: null,
    maxRank: 1,
    costPerRank: 3,
    requiredLevel: 9,
    requires: ["aegis-core-unbroken-line"],
    position: { x: 50, y: 75 },
    effects: [
      { type: "low_health_hp_percent", value: 6 },
      { type: "low_health_defense_percent", value: 4 },
    ],
  },
  {
    id: "aegis-capstone-aegis-of-the-pack",
    tree: "aegis",
    branch: "merge",
    shape: "triangle",
    name: "Aegis of the Pack",
    description:
      "+10% damage reduction, +10% shield value, and +8% threat generation.",
    tradeoff: "-5% speed.",
    maxRank: 1,
    costPerRank: 4,
    requiredLevel: 10,
    requires: [
      "aegis-warrior-iron-vanguard",
      "aegis-sentinel-living-fortress",
      "aegis-core-last-stand",
    ],
    position: { x: 50, y: 90 },
    effects: [
      { type: "damage_reduction", value: 10 },
      { type: "shield_value", value: 10 },
      { type: "threat_generation", value: 8 },
      { type: "speed_percent", value: -5 },
    ],
  },
];
