import type { TalentNode } from "../talentTreeRegistry";
import { FERAL_NODES } from "./feralPath";

export const FERAL_SKILL_NODES: TalentNode[] = [
  {
    id: "feral-start",
    tree: "feral",
    branch: "merge",
    name: "Savage Might",
    description: "+4 Attack per rank. Core Feral power.",
    maxRank: 3,
    costPerRank: 1,
    requiredLevel: 1,
    requires: [],
    position: { x: 50, y: 6 },
    effects: [{ type: "attack", value: 4 }],
  },

  {
    id: "feral-bleed-1",
    tree: "feral",
    branch: "bleed",
    name: "Razor Claws",
    description: "Basic attacks gain bleed chance.",
    maxRank: 3,
    costPerRank: 1,
    requiredLevel: 2,
    requires: ["feral-start"],
    position: { x: 28, y: 16 },
    effects: [{ type: "bleed_chance", value: 6 }],
  },
  {
    id: "feral-attack-1",
    tree: "feral",
    branch: "attack",
    name: "Ferocious Strike",
    description: "+3 Attack per rank.",
    maxRank: 3,
    costPerRank: 1,
    requiredLevel: 2,
    requires: ["feral-start"],
    position: { x: 72, y: 16 },
    effects: [{ type: "attack", value: 3 }],
  },

  {
    id: "feral-bleed-2",
    tree: "feral",
    branch: "bleed",
    name: "Open Wounds",
    description: "Bleed damage is stronger.",
    maxRank: 2,
    costPerRank: 1,
    requiredLevel: 3,
    requires: ["feral-bleed-1"],
    position: { x: 28, y: 25 },
    effects: [{ type: "bleed_power", value: 8 }],
  },
  {
    id: "feral-attack-2",
    tree: "feral",
    branch: "attack",
    name: "Predator Strength",
    description: "+5 Attack per rank.",
    maxRank: 2,
    costPerRank: 1,
    requiredLevel: 3,
    requires: ["feral-attack-1"],
    position: { x: 72, y: 25 },
    effects: [{ type: "attack", value: 5 }],
  },

  {
    id: "feral-merge-1",
    tree: "feral",
    branch: "merge",
    name: "Blood-Fueled Strike",
    description: "Attacks hit harder against bleeding enemies.",
    maxRank: 2,
    costPerRank: 1,
    requiredLevel: 4,
    requires: ["feral-bleed-2", "feral-attack-2"],
    position: { x: 50, y: 34 },
    effects: [
      { type: "attack", value: 3 },
      { type: "bleed_bonus_damage", value: 6 },
    ],
  },

  {
    id: "feral-bleed-3",
    tree: "feral",
    branch: "bleed",
    name: "Serrated Claws",
    description: "Increases bleed chance.",
    maxRank: 2,
    costPerRank: 1,
    requiredLevel: 5,
    requires: ["feral-merge-1"],
    position: { x: 28, y: 43 },
    effects: [{ type: "bleed_chance", value: 8 }],
  },
  {
    id: "feral-attack-3",
    tree: "feral",
    branch: "attack",
    name: "Crushing Claws",
    description: "Basic Strike deals more damage.",
    maxRank: 2,
    costPerRank: 1,
    requiredLevel: 5,
    requires: ["feral-merge-1"],
    position: { x: 72, y: 43 },
    effects: [{ type: "basic_strike_bonus_damage", value: 8 }],
  },

  {
    id: "feral-bleed-4",
    tree: "feral",
    branch: "bleed",
    name: "Blood Scent",
    description: "Bonus damage to bleeding enemies.",
    maxRank: 2,
    costPerRank: 1,
    requiredLevel: 6,
    requires: ["feral-bleed-3"],
    position: { x: 28, y: 52 },
    effects: [{ type: "bleed_bonus_damage", value: 7 }],
  },
  {
    id: "feral-attack-4",
    tree: "feral",
    branch: "attack",
    name: "Hunt Pressure",
    description: "+4 Attack and +4 Health per rank.",
    maxRank: 2,
    costPerRank: 1,
    requiredLevel: 6,
    requires: ["feral-attack-3"],
    position: { x: 72, y: 52 },
    effects: [
      { type: "attack", value: 4 },
      { type: "health", value: 4 },
    ],
  },

  {
    id: "feral-merge-2",
    tree: "feral",
    branch: "merge",
    name: "Rend and Rush",
    description: "Bleed effects make your next attack stronger.",
    maxRank: 2,
    costPerRank: 1,
    requiredLevel: 7,
    requires: ["feral-bleed-4", "feral-attack-4"],
    position: { x: 50, y: 61 },
    effects: [
      { type: "bleed_power", value: 8 },
      { type: "attack", value: 5 },
    ],
  },

  {
    id: "feral-bleed-5",
    tree: "feral",
    branch: "bleed",
    name: "Deep Wounds",
    description: "Bleed lasts longer and ticks harder.",
    maxRank: 2,
    costPerRank: 1,
    requiredLevel: 8,
    requires: ["feral-merge-2"],
    position: { x: 28, y: 70 },
    effects: [{ type: "bleed_power", value: 12 }],
  },
  {
    id: "feral-attack-5",
    tree: "feral",
    branch: "attack",
    name: "Maul Instinct",
    description: "Basic Strike has a chance to hit harder.",
    maxRank: 2,
    costPerRank: 1,
    requiredLevel: 8,
    requires: ["feral-merge-2"],
    position: { x: 72, y: 70 },
    effects: [{ type: "basic_strike_bonus_damage", value: 10 }],
  },

  {
    id: "feral-bleed-6",
    tree: "feral",
    branch: "bleed",
    name: "Scarred Hide",
    description: "+6 Health per rank.",
    maxRank: 2,
    costPerRank: 1,
    requiredLevel: 8,
    requires: ["feral-bleed-5"],
    position: { x: 18, y: 78 },
    effects: [{ type: "health", value: 6 }],
  },
  {
    id: "feral-attack-6",
    tree: "feral",
    branch: "attack",
    name: "Apex Muscle",
    description: "+6 Attack per rank.",
    maxRank: 2,
    costPerRank: 1,
    requiredLevel: 8,
    requires: ["feral-attack-5"],
    position: { x: 82, y: 78 },
    effects: [{ type: "attack", value: 6 }],
  },

  {
    id: "feral-merge-3",
    tree: "feral",
    branch: "merge",
    name: "Predator Flow",
    description: "Bleed bonuses and attack buffs feed into each other.",
    maxRank: 2,
    costPerRank: 1,
    requiredLevel: 9,
    requires: ["feral-bleed-6", "feral-attack-6"],
    position: { x: 50, y: 84 },
    effects: [
      { type: "attack", value: 6 },
      { type: "bleed_bonus_damage", value: 8 },
    ],
  },

  {
    id: "feral-bleed-7",
    tree: "feral",
    branch: "bleed",
    name: "Blood Hunter",
    description: "Bonus damage against wounded or bleeding enemies.",
    maxRank: 2,
    costPerRank: 1,
    requiredLevel: 9,
    requires: ["feral-merge-3"],
    position: { x: 35, y: 91 },
    effects: [{ type: "wounded_bonus_damage", value: 6 }],
  },
  {
    id: "feral-attack-7",
    tree: "feral",
    branch: "attack",
    name: "Finishing Bite",
    description: "Deal bonus damage to wounded enemies.",
    maxRank: 2,
    costPerRank: 1,
    requiredLevel: 9,
    requires: ["feral-merge-3"],
    position: { x: 65, y: 91 },
    effects: [{ type: "wounded_bonus_damage", value: 8 }],
  },

  {
    id: "feral-capstone-bleed",
    tree: "feral",
    branch: "capstone",
    name: "Apex Rend",
    description: "Final bleed talent. Massive damage against bleeding enemies.",
    maxRank: 1,
    costPerRank: 3,
    requiredLevel: 10,
    requires: ["feral-bleed-7"],
    position: { x: 35, y: 98 },
    effects: [
      { type: "bleed_power", value: 18 },
      { type: "wounded_bonus_damage", value: 16 },
    ],
  },
  {
    id: "feral-capstone-attack",
    tree: "feral",
    branch: "capstone",
    name: "Apex Maul",
    description: "Final attack talent. Heavy physical damage with extra bulk.",
    maxRank: 1,
    costPerRank: 3,
    requiredLevel: 10,
    requires: ["feral-attack-7"],
    position: { x: 65, y: 98 },
    effects: [
      { type: "attack", value: 14 },
      { type: "defense", value: 6 },
      { type: "health", value: 12 },
    ],
  },
];
