import type { TalentNode } from "../talentTreeRegistry";

// ─── FERAL TALENT TREE ──────────────────────────────────────
//
// 20 talents | 2 specs: Bleed Specialist + Ravager
//
// Bleed Specialist:
//   Damage over time, longer wounds, bonus damage vs bleeding targets.
//
// Ravager:
//   High attack power, burst damage, lower defense / risky glass cannon play.
//
// Core Feral:
//   Shared attack/speed pressure that supports both builds.
//
// IMPORTANT:
// Do not move node positions. The layout spacing is already good.
// ────────────────────────────────────────────────────────────

export const FERAL_NODES: TalentNode[] = [
  {
    id: "feral-root",
    tree: "feral",
    branch: "merge",
    shape: "square",
    name: "Feral Instinct",
    description: "+3% ATK per rank. Core Feral power. Unlocks the tree.",
    tradeoff: null,
    maxRank: 4,
    costPerRank: 1,
    requiredLevel: 1,
    requires: [],
    position: { x: 50, y: 11 },
    effects: [{ type: "attack_percent", value: 3 }],
  },

  {
    id: "feral-crimson-fangs",
    tree: "feral",
    branch: "bleed",
    shape: "circle",
    name: "Crimson Fangs",
    description:
      "Attacks gain 5% bleed chance per rank. This starts the Bleed Specialist path.",
    tradeoff: null,
    maxRank: 3,
    costPerRank: 1,
    requiredLevel: 2,
    requires: [],
    position: { x: 20, y: 25 },
    effects: [{ type: "bleed_chance", value: 5 }],
  },
  {
    id: "feral-fang-over-fang",
    tree: "feral",
    branch: "attack",
    shape: "circle",
    name: "Ravage Rhythm",
    description:
      "Each consecutive hit within 4s grants +2% ATK. Stacks 5x. Resets on miss.",
    tradeoff: "Aggressive pressure rewards clean attacks.",
    maxRank: 3,
    costPerRank: 1,
    requiredLevel: 2,
    requires: [],
    position: { x: 50, y: 25 },
    effects: [{ type: "attack_percent", value: 2 }],
  },
  {
    id: "feral-reckless-charge",
    tree: "feral",
    branch: "attack",
    shape: "circle",
    name: "Reckless Charge",
    description:
      "First attack in combat deals bonus damage. A Ravager opener built for big numbers.",
    tradeoff: "-1 DEF per rank. Hits harder, survives worse.",
    maxRank: 3,
    costPerRank: 1,
    requiredLevel: 2,
    requires: [],
    position: { x: 80, y: 25 },
    effects: [
      { type: "attack", value: 4 },
      { type: "defense", value: -1 },
    ],
  },

  {
    id: "feral-savage-rend",
    tree: "feral",
    branch: "bleed",
    shape: "circle",
    name: "Savage Rend",
    description:
      "Bleed duration increases and bleed ticks deal 10% more damage per rank.",
    tradeoff: null,
    maxRank: 2,
    costPerRank: 1,
    requiredLevel: 3,
    requires: [],
    position: { x: 10, y: 39 },
    effects: [{ type: "bleed_power", value: 10 }],
  },
  {
    id: "feral-blood-scent",
    tree: "feral",
    branch: "bleed",
    shape: "circle",
    name: "Blood Scent",
    description: "+8% damage against bleeding targets per rank.",
    tradeoff: null,
    maxRank: 2,
    costPerRank: 1,
    requiredLevel: 3,
    requires: [],
    position: { x: 30, y: 39 },
    effects: [{ type: "bleed_bonus_damage", value: 8 }],
  },
  {
    id: "feral-swift-predator",
    tree: "feral",
    branch: "attack",
    shape: "circle",
    name: "Swift Predator",
    description: "+4% SPD per rank. Faster attacks for both Feral builds.",
    tradeoff: null,
    maxRank: 2,
    costPerRank: 1,
    requiredLevel: 3,
    requires: [],
    position: { x: 50, y: 39 },
    effects: [{ type: "speed_percent", value: 4 }],
  },
  {
    id: "feral-blur-step",
    tree: "feral",
    branch: "attack",
    shape: "circle",
    name: "Armor Splitter",
    description: "+5% ATK per rank when striking enemies above 50% HP.",
    tradeoff: "-2% DEF per rank. Ravagers break things, including themselves.",
    maxRank: 2,
    costPerRank: 1,
    requiredLevel: 3,
    requires: [],
    position: { x: 70, y: 39 },
    effects: [
      { type: "attack_percent", value: 5 },
      { type: "defense_percent", value: -2 },
    ],
  },
  {
    id: "feral-adrenaline-spike",
    tree: "feral",
    branch: "attack",
    shape: "circle",
    name: "Adrenaline Spike",
    description: "Below 40% HP, gain 10% SPD. Panic power, very feral.",
    tradeoff: null,
    maxRank: 2,
    costPerRank: 1,
    requiredLevel: 3,
    requires: [],
    position: { x: 90, y: 39 },
    effects: [{ type: "speed_percent", value: 10 }],
  },

  {
    id: "feral-shred-storm",
    tree: "feral",
    branch: "bleed",
    shape: "triangle",
    name: "Shred Storm",
    description: "Bleed has a 20% chance to spread to a nearby enemy on tick.",
    tradeoff: null,
    maxRank: 1,
    costPerRank: 2,
    requiredLevel: 5,
    requires: [],
    position: { x: 20, y: 53 },
    effects: [{ type: "shred_storm_active", value: 1 }],
  },
  {
    id: "feral-phantom-strikes",
    tree: "feral",
    branch: "attack",
    shape: "triangle",
    name: "Phantom Strikes",
    description: "10% chance per rank for attacks to hit twice at 60% damage.",
    tradeoff: "-3% DEF per rank. More claws, less caution.",
    maxRank: 2,
    costPerRank: 2,
    requiredLevel: 5,
    requires: [],
    position: { x: 50, y: 53 },
    effects: [
      { type: "double_attack_chance", value: 10 },
      { type: "defense_percent", value: -3 },
    ],
  },
  {
    id: "feral-rush-synergy",
    tree: "feral",
    branch: "attack",
    shape: "triangle",
    name: "Ravage Break",
    description:
      "Heavy strikes deal 50% ATK bonus damage when the target is not bleeding.",
    tradeoff: "Built for raw DPS, not safety.",
    maxRank: 1,
    costPerRank: 2,
    requiredLevel: 5,
    requires: [],
    position: { x: 80, y: 53 },
    effects: [{ type: "basic_strike_bonus_damage", value: 50 }],
  },

  {
    id: "feral-pain-engine",
    tree: "feral",
    branch: "bleed",
    shape: "triangle",
    name: "Pain Engine",
    description: "Each bleed tick grants +1% ATK for 6s. Stacks.",
    tradeoff: null,
    maxRank: 2,
    costPerRank: 2,
    requiredLevel: 7,
    requires: [],
    position: { x: 15, y: 65 },
    effects: [{ type: "damage_taken_attack_stack", value: 1 }],
  },
  {
    id: "feral-deathwish-gambit",
    tree: "feral",
    branch: "bleed",
    shape: "triangle",
    name: "Deathwish Gambit",
    description: "Below 20% HP, gain 25% ATK and bleed immunity on self.",
    tradeoff: "No safety net. Pure desperation power.",
    maxRank: 1,
    costPerRank: 3,
    requiredLevel: 7,
    requires: [],
    position: { x: 40, y: 65 },
    effects: [{ type: "deathwish_active", value: 1 }],
  },
  {
    id: "feral-frenzy-state",
    tree: "feral",
    branch: "attack",
    shape: "triangle",
    name: "Frenzy State",
    description: "After landing 10 hits in a fight, gain +12% ATK.",
    tradeoff: "-6% DEF while active. Glass cannon mode, baby.",
    maxRank: 1,
    costPerRank: 2,
    requiredLevel: 7,
    requires: [],
    position: { x: 60, y: 65 },
    effects: [
      { type: "attack_percent", value: 12 },
      { type: "defense_percent", value: -6 },
    ],
  },
  {
    id: "feral-last-breath",
    tree: "feral",
    branch: "attack",
    shape: "triangle",
    name: "Last Breath",
    description: "Survive a killing blow once per battle with 1 HP.",
    tradeoff: null,
    maxRank: 1,
    costPerRank: 3,
    requiredLevel: 7,
    requires: [],
    position: { x: 85, y: 65 },
    effects: [{ type: "death_save", value: 1 }],
  },

  {
    id: "feral-primal-fury",
    tree: "feral",
    branch: "merge",
    shape: "square",
    name: "Primal Fury",
    description: "Activate primal pressure to reduce enemy DEF by 12% for 6s.",
    tradeoff: null,
    maxRank: 1,
    costPerRank: 3,
    requiredLevel: 9,
    requires: [],
    position: { x: 35, y: 79 },
    effects: [{ type: "defense_percent", value: -12 }],
  },
  {
    id: "feral-blood-debt",
    tree: "feral",
    branch: "bleed",
    shape: "square",
    name: "Blood Debt",
    description: "15% of bleed damage dealt is returned as self-heal.",
    tradeoff: null,
    maxRank: 1,
    costPerRank: 3,
    requiredLevel: 9,
    requires: [],
    position: { x: 65, y: 79 },
    effects: [{ type: "blood_debt_reflect", value: 15 }],
  },
  {
    id: "feral-extinction",
    tree: "feral",
    branch: "capstone",
    shape: "triangle",
    name: "Extinction",
    description:
      "All damage +10%. Bleeding targets take 5% more damage. On kill, restore 5% max HP.",
    tradeoff: "Ultimate Feral payoff.",
    maxRank: 1,
    costPerRank: 4,
    requiredLevel: 10,
    requires: [],
    position: { x: 50, y: 90 },
    effects: [
      { type: "apex_scaling", value: 10 },
      { type: "bleed_bonus_damage", value: 5 },
      { type: "kill_reset", value: 5 },
    ],
  },
];
