import type { TalentNode } from "../talentTreeRegistry";

export const HYBRID_NODES: TalentNode[] = [
  {
    id: "hybrid-root",
    tree: "hybrid",
    branch: "merge",
    shape: "square",
    name: "Triune Instinct",
    description: "+1% ATK, +1% DEF, and +1% MAGI per rank. Unlocks the tree.",
    tradeoff: null,
    maxRank: 4,
    costPerRank: 1,
    requiredLevel: 1,
    requires: [],
    position: { x: 50, y: 11 },
    effects: [
      { type: "attack_percent", value: 1 },
      { type: "defense_percent", value: 1 },
      { type: "magi_percent", value: 1 },
    ],
  },
  {
    id: "hybrid-feral-guarded-strike",
    tree: "hybrid",
    branch: "attack",
    shape: "circle",
    name: "Guarded Strike",
    description: "+3% ATK and +2% DEF per rank.",
    tradeoff: null,
    maxRank: 3,
    costPerRank: 1,
    requiredLevel: 2,
    requires: ["hybrid-root"],
    position: { x: 20, y: 25 },
    effects: [
      { type: "attack_percent", value: 3 },
      { type: "defense_percent", value: 2 },
    ],
  },
  {
    id: "hybrid-aegis-mystic-shell",
    tree: "hybrid",
    branch: "sentinel",
    shape: "circle",
    name: "Mystic Shell",
    description: "+3% DEF and +2% MAGI per rank.",
    tradeoff: null,
    maxRank: 3,
    costPerRank: 1,
    requiredLevel: 2,
    requires: ["hybrid-root"],
    position: { x: 50, y: 25 },
    effects: [
      { type: "defense_percent", value: 3 },
      { type: "magi_percent", value: 2 },
    ],
  },
  {
    id: "hybrid-majo-wild-spark",
    tree: "hybrid",
    branch: "sorcerer",
    shape: "circle",
    name: "Wild Spark",
    description: "+3% MAGI and +2% ATK per rank.",
    tradeoff: null,
    maxRank: 3,
    costPerRank: 1,
    requiredLevel: 2,
    requires: ["hybrid-root"],
    position: { x: 80, y: 25 },
    effects: [
      { type: "magi_percent", value: 3 },
      { type: "attack_percent", value: 2 },
    ],
  },
  {
    id: "hybrid-feral-counterfang",
    tree: "hybrid",
    branch: "attack",
    shape: "circle",
    name: "Counterfang",
    description: "+4% counter-attack damage per rank.",
    tradeoff: null,
    maxRank: 2,
    costPerRank: 1,
    requiredLevel: 3,
    requires: ["hybrid-feral-guarded-strike"],
    position: { x: 10, y: 39 },
    effects: [{ type: "counter_attack_damage", value: 4 }],
  },
  {
    id: "hybrid-feral-warded-rush",
    tree: "hybrid",
    branch: "attack",
    shape: "circle",
    name: "Warded Rush",
    description: "+4% SPD and +2% shield value per rank.",
    tradeoff: null,
    maxRank: 2,
    costPerRank: 1,
    requiredLevel: 3,
    requires: ["hybrid-feral-guarded-strike"],
    position: { x: 30, y: 39 },
    effects: [
      { type: "speed_percent", value: 4 },
      { type: "shield_value", value: 2 },
    ],
  },
  {
    id: "hybrid-core-balanced-flow",
    tree: "hybrid",
    branch: "merge",
    shape: "circle",
    name: "Balanced Flow",
    description: "+2% HP, +2% mana, and +2% SPD per rank.",
    tradeoff: null,
    maxRank: 2,
    costPerRank: 1,
    requiredLevel: 3,
    requires: ["hybrid-root"],
    position: { x: 50, y: 39 },
    effects: [
      { type: "hp_percent", value: 2 },
      { type: "mana_percent", value: 2 },
      { type: "speed_percent", value: 2 },
    ],
  },
  {
    id: "hybrid-majo-restoring-blow",
    tree: "hybrid",
    branch: "healer",
    shape: "circle",
    name: "Restoring Blow",
    description: "+3% heal power and +3% ATK per rank.",
    tradeoff: null,
    maxRank: 2,
    costPerRank: 1,
    requiredLevel: 3,
    requires: ["hybrid-majo-wild-spark"],
    position: { x: 70, y: 39 },
    effects: [
      { type: "heal_power", value: 3 },
      { type: "attack_percent", value: 3 },
    ],
  },
  {
    id: "hybrid-aegis-arcane-guard",
    tree: "hybrid",
    branch: "sentinel",
    shape: "circle",
    name: "Arcane Guard",
    description: "+4% shield value and +3% spell damage per rank.",
    tradeoff: null,
    maxRank: 2,
    costPerRank: 1,
    requiredLevel: 3,
    requires: ["hybrid-aegis-mystic-shell"],
    position: { x: 90, y: 39 },
    effects: [
      { type: "shield_value", value: 4 },
      { type: "spell_damage_percent", value: 3 },
    ],
  },
  {
    id: "hybrid-feral-bastion-breaker",
    tree: "hybrid",
    branch: "attack",
    shape: "triangle",
    name: "Bastion Breaker",
    description: "+6% ATK and +3% damage reduction per rank.",
    tradeoff: "-2% mana per rank.",
    maxRank: 2,
    costPerRank: 2,
    requiredLevel: 5,
    requires: ["hybrid-feral-counterfang", "hybrid-feral-warded-rush"],
    position: { x: 20, y: 53 },
    effects: [
      { type: "attack_percent", value: 6 },
      { type: "damage_reduction", value: 3 },
      { type: "mana_percent", value: -2 },
    ],
  },
  {
    id: "hybrid-core-role-shift",
    tree: "hybrid",
    branch: "merge",
    shape: "triangle",
    name: "Role Shift",
    description: "+4% ATK and +4% DEF per rank.",
    tradeoff: null,
    maxRank: 2,
    costPerRank: 2,
    requiredLevel: 5,
    requires: ["hybrid-core-balanced-flow"],
    position: { x: 50, y: 53 },
    effects: [{ type: "attack_defense", value: 4 }],
  },
  {
    id: "hybrid-majo-radiant-claw",
    tree: "hybrid",
    branch: "sorcerer",
    shape: "triangle",
    name: "Radiant Claw",
    description: "+5% spell damage and +4% heal power per rank.",
    tradeoff: "-2% DEF per rank.",
    maxRank: 2,
    costPerRank: 2,
    requiredLevel: 5,
    requires: ["hybrid-majo-restoring-blow", "hybrid-aegis-arcane-guard"],
    position: { x: 80, y: 53 },
    effects: [
      { type: "spell_damage_percent", value: 5 },
      { type: "heal_power", value: 4 },
      { type: "defense_percent", value: -2 },
    ],
  },
  {
    id: "hybrid-feral-guardian-instinct",
    tree: "hybrid",
    branch: "warrior",
    shape: "triangle",
    name: "Guardian Instinct",
    description: "Below 40% HP, gain +8% ATK and +8% DEF per rank.",
    tradeoff: null,
    maxRank: 2,
    costPerRank: 2,
    requiredLevel: 7,
    requires: ["hybrid-feral-bastion-breaker"],
    position: { x: 15, y: 65 },
    effects: [
      { type: "attack_percent", value: 8 },
      { type: "low_health_defense_percent", value: 8 },
    ],
  },
  {
    id: "hybrid-aegis-spellwall",
    tree: "hybrid",
    branch: "sentinel",
    shape: "triangle",
    name: "Spellwall",
    description: "+5% party shield value and +4% mana efficiency per rank.",
    tradeoff: null,
    maxRank: 2,
    costPerRank: 2,
    requiredLevel: 7,
    requires: ["hybrid-core-role-shift"],
    position: { x: 40, y: 65 },
    effects: [
      { type: "party_shield_value", value: 5 },
      { type: "mana_efficiency", value: 4 },
    ],
  },
  {
    id: "hybrid-majo-predators-grace",
    tree: "hybrid",
    branch: "healer",
    shape: "triangle",
    name: "Predator's Grace",
    description: "+5% party heal power and +4% SPD per rank.",
    tradeoff: null,
    maxRank: 2,
    costPerRank: 2,
    requiredLevel: 7,
    requires: ["hybrid-majo-radiant-claw"],
    position: { x: 60, y: 65 },
    effects: [
      { type: "party_heal_power", value: 5 },
      { type: "speed_percent", value: 4 },
    ],
  },
  {
    id: "hybrid-core-threefold-pulse",
    tree: "hybrid",
    branch: "merge",
    shape: "triangle",
    name: "Threefold Pulse",
    description: "+4% ATK, +4% DEF, and +4% MAGI per rank.",
    tradeoff: "-3% HP per rank.",
    maxRank: 2,
    costPerRank: 2,
    requiredLevel: 7,
    requires: ["hybrid-core-role-shift"],
    position: { x: 85, y: 65 },
    effects: [
      { type: "attack_percent", value: 4 },
      { type: "defense_percent", value: 4 },
      { type: "magi_percent", value: 4 },
      { type: "hp_percent", value: -3 },
    ],
  },
  {
    id: "hybrid-feral-iron-tempest",
    tree: "hybrid",
    branch: "warrior",
    shape: "square",
    name: "Iron Tempest",
    description: "+8% ATK, +6% counter damage, and +5% damage reduction.",
    tradeoff: "-4% MAGI.",
    maxRank: 1,
    costPerRank: 3,
    requiredLevel: 9,
    requires: ["hybrid-feral-guardian-instinct"],
    position: { x: 25, y: 79 },
    effects: [
      { type: "attack_percent", value: 8 },
      { type: "counter_attack_damage", value: 6 },
      { type: "damage_reduction", value: 5 },
      { type: "magi_percent", value: -4 },
    ],
  },
  {
    id: "hybrid-aegis-arcane-sanctuary",
    tree: "hybrid",
    branch: "sentinel",
    shape: "square",
    name: "Arcane Sanctuary",
    description: "+8% party shield value, +6% heal power, and +5% MAGI.",
    tradeoff: "-4% ATK.",
    maxRank: 1,
    costPerRank: 3,
    requiredLevel: 9,
    requires: ["hybrid-aegis-spellwall", "hybrid-majo-predators-grace"],
    position: { x: 50, y: 79 },
    effects: [
      { type: "party_shield_value", value: 8 },
      { type: "heal_power", value: 6 },
      { type: "magi_percent", value: 5 },
      { type: "attack_percent", value: -4 },
    ],
  },
  {
    id: "hybrid-majo-savage-convergence",
    tree: "hybrid",
    branch: "sorcerer",
    shape: "square",
    name: "Savage Convergence",
    description: "+8% spell damage, +6% ATK, and +5% shield value.",
    tradeoff: "-4% DEF.",
    maxRank: 1,
    costPerRank: 3,
    requiredLevel: 9,
    requires: ["hybrid-majo-predators-grace", "hybrid-core-threefold-pulse"],
    position: { x: 75, y: 79 },
    effects: [
      { type: "spell_damage_percent", value: 8 },
      { type: "attack_percent", value: 6 },
      { type: "shield_value", value: 5 },
      { type: "defense_percent", value: -4 },
    ],
  },
  {
    id: "hybrid-capstone-perfect-balance",
    tree: "hybrid",
    branch: "capstone",
    shape: "square",
    name: "Perfect Balance",
    description: "+7% to HP, ATK, DEF, SPD, MAGI, and mana.",
    tradeoff: null,
    maxRank: 1,
    costPerRank: 4,
    requiredLevel: 10,
    requires: [
      "hybrid-feral-iron-tempest",
      "hybrid-aegis-arcane-sanctuary",
      "hybrid-majo-savage-convergence",
    ],
    position: { x: 50, y: 92 },
    effects: [
      { type: "hp_percent", value: 7 },
      { type: "attack_percent", value: 7 },
      { type: "defense_percent", value: 7 },
      { type: "speed_percent", value: 7 },
      { type: "magi_percent", value: 7 },
      { type: "mana_percent", value: 7 },
    ],
  },
];
