import type { TalentNode } from "../talentTreeRegistry";

// ─── MAJO TALENT TREE ───────────────────────────────────────
//
// 20 talents | 2 specs: Sorcerer + Healer
//
// Sorcerer:
//   Magic damage, burst spells, elemental pressure,
//   status effects, and risky spell power scaling.
//
// Healer:
//   HP restoration, party heals, cleanse support,
//   mana efficiency, and protective buffs.
//
// Core Majo:
//   Shared MAGI/mana pressure that supports both caster builds.
//
// IMPORTANT:
// Keep node positions aligned with the Feral board rhythm.
// Majo has one extra core square, so the square row uses three slots.
// ────────────────────────────────────────────────────────────

export const MAJO_NODES: TalentNode[] = [
  {
    id: "majo-root",
    tree: "majo",
    branch: "merge",
    shape: "square",
    name: "Majo Spark",
    description: "+3% MAGI per rank. Core Majo power. Unlocks the tree.",
    tradeoff: null,
    maxRank: 4,
    costPerRank: 1,
    requiredLevel: 1,
    requires: [],
    position: { x: 50, y: 11 },
    effects: [{ type: "magi_percent", value: 3 }],
  },
  {
    id: "majo-sorcerer-arcane-bite",
    tree: "majo",
    branch: "sorcerer",
    shape: "circle",
    name: "Arcane Bite",
    description: "+3% spell damage per rank.",
    tradeoff: null,
    maxRank: 3,
    costPerRank: 1,
    requiredLevel: 2,
    requires: ["majo-root"],
    position: { x: 20, y: 25 },
    effects: [{ type: "spell_damage_percent", value: 3 }],
  },
  {
    id: "majo-healer-soft-mending",
    tree: "majo",
    branch: "healer",
    shape: "circle",
    name: "Soft Mending",
    description: "+4% heal power per rank.",
    tradeoff: null,
    maxRank: 3,
    costPerRank: 1,
    requiredLevel: 2,
    requires: ["majo-root"],
    position: { x: 80, y: 25 },
    effects: [{ type: "heal_power", value: 4 }],
  },
  {
    id: "majo-core-mana-thread",
    tree: "majo",
    branch: "merge",
    shape: "circle",
    name: "Mana Thread",
    description: "+3% mana per rank.",
    tradeoff: null,
    maxRank: 3,
    costPerRank: 1,
    requiredLevel: 3,
    requires: ["majo-root"],
    position: { x: 50, y: 25 },
    effects: [{ type: "mana_percent", value: 3 }],
  },
  {
    id: "majo-sorcerer-burst-rune",
    tree: "majo",
    branch: "sorcerer",
    shape: "circle",
    name: "Burst Rune",
    description: "+4% burst spell damage per rank.",
    tradeoff: "-1% DEF per rank.",
    maxRank: 3,
    costPerRank: 1,
    requiredLevel: 3,
    requires: ["majo-sorcerer-arcane-bite"],
    position: { x: 10, y: 39 },
    effects: [
      { type: "burst_spell_damage", value: 4 },
      { type: "defense_percent", value: -1 },
    ],
  },
  {
    id: "majo-sorcerer-elemental-prick",
    tree: "majo",
    branch: "sorcerer",
    shape: "circle",
    name: "Elemental Prick",
    description: "+5% status effect chance per rank.",
    tradeoff: null,
    maxRank: 3,
    costPerRank: 1,
    requiredLevel: 3,
    requires: ["majo-sorcerer-arcane-bite"],
    position: { x: 30, y: 39 },
    effects: [{ type: "status_effect_chance", value: 5 }],
  },
  {
    id: "majo-healer-bright-pulse",
    tree: "majo",
    branch: "healer",
    shape: "circle",
    name: "Bright Pulse",
    description: "+3% party heal power per rank.",
    tradeoff: null,
    maxRank: 3,
    costPerRank: 1,
    requiredLevel: 3,
    requires: ["majo-healer-soft-mending"],
    position: { x: 70, y: 39 },
    effects: [{ type: "party_heal_power", value: 3 }],
  },
  {
    id: "majo-healer-cleanse-charm",
    tree: "majo",
    branch: "healer",
    shape: "circle",
    name: "Cleanse Charm",
    description: "+6% cleanse chance per rank.",
    tradeoff: null,
    maxRank: 3,
    costPerRank: 1,
    requiredLevel: 3,
    requires: ["majo-healer-soft-mending"],
    position: { x: 90, y: 39 },
    effects: [{ type: "cleanse_chance", value: 6 }],
  },
  {
    id: "majo-core-deep-focus",
    tree: "majo",
    branch: "merge",
    shape: "circle",
    name: "Deep Focus",
    description: "+2% MAGI and +2% mana per rank.",
    tradeoff: null,
    maxRank: 3,
    costPerRank: 1,
    requiredLevel: 5,
    requires: ["majo-core-mana-thread"],
    position: { x: 50, y: 39 },
    effects: [
      { type: "magi_percent", value: 2 },
      { type: "mana_percent", value: 2 },
    ],
  },
  {
    id: "majo-sorcerer-volatile-cast",
    tree: "majo",
    branch: "sorcerer",
    shape: "triangle",
    name: "Volatile Cast",
    description: "+5% spell critical chance per rank.",
    tradeoff: "-2% HP per rank.",
    maxRank: 3,
    costPerRank: 2,
    requiredLevel: 5,
    requires: ["majo-sorcerer-burst-rune"],
    position: { x: 20, y: 53 },
    effects: [
      { type: "spell_crit_chance", value: 5 },
      { type: "hp_percent", value: -2 },
    ],
  },
  {
    id: "majo-sorcerer-burning-mark",
    tree: "majo",
    branch: "sorcerer",
    shape: "triangle",
    name: "Burning Mark",
    description: "+4% status damage per rank.",
    tradeoff: null,
    maxRank: 3,
    costPerRank: 2,
    requiredLevel: 5,
    requires: ["majo-sorcerer-elemental-prick"],
    position: { x: 15, y: 65 },
    effects: [{ type: "status_damage_percent", value: 4 }],
  },
  {
    id: "majo-healer-wellspring",
    tree: "majo",
    branch: "healer",
    shape: "triangle",
    name: "Wellspring",
    description: "+4% heal over time power per rank.",
    tradeoff: null,
    maxRank: 3,
    costPerRank: 2,
    requiredLevel: 5,
    requires: ["majo-healer-bright-pulse"],
    position: { x: 60, y: 65 },
    effects: [{ type: "heal_over_time_power", value: 4 }],
  },
  {
    id: "majo-healer-kindled-ward",
    tree: "majo",
    branch: "healer",
    shape: "triangle",
    name: "Kindled Ward",
    description: "+3% healing buff power per rank.",
    tradeoff: "-1% ATK per rank.",
    maxRank: 3,
    costPerRank: 2,
    requiredLevel: 5,
    requires: ["majo-healer-cleanse-charm"],
    position: { x: 80, y: 53 },
    effects: [
      { type: "healing_buff_power", value: 3 },
      { type: "attack_percent", value: -1 },
    ],
  },
  {
    id: "majo-core-mana-loop",
    tree: "majo",
    branch: "merge",
    shape: "triangle",
    name: "Mana Loop",
    description: "+4% mana efficiency per rank.",
    tradeoff: null,
    maxRank: 3,
    costPerRank: 2,
    requiredLevel: 7,
    requires: ["majo-core-deep-focus"],
    position: { x: 50, y: 53 },
    effects: [{ type: "mana_efficiency", value: 4 }],
  },
  {
    id: "majo-sorcerer-starfall-surge",
    tree: "majo",
    branch: "sorcerer",
    shape: "triangle",
    name: "Starfall Surge",
    description: "+5% spell damage and +4% status effect chance per rank.",
    tradeoff: null,
    maxRank: 2,
    costPerRank: 2,
    requiredLevel: 7,
    requires: ["majo-sorcerer-volatile-cast", "majo-sorcerer-burning-mark"],
    position: { x: 40, y: 65 },
    effects: [
      { type: "spell_damage_percent", value: 5 },
      { type: "status_effect_chance", value: 4 },
    ],
  },
  {
    id: "majo-healer-moonwell-grace",
    tree: "majo",
    branch: "healer",
    shape: "triangle",
    name: "Moonwell Grace",
    description: "+5% party heal power and +4% cleanse chance per rank.",
    tradeoff: null,
    maxRank: 2,
    costPerRank: 2,
    requiredLevel: 7,
    requires: ["majo-healer-wellspring", "majo-healer-kindled-ward"],
    position: { x: 85, y: 65 },
    effects: [
      { type: "party_heal_power", value: 5 },
      { type: "cleanse_chance", value: 4 },
    ],
  },
  {
    id: "majo-sorcerer-arcane-overload",
    tree: "majo",
    branch: "sorcerer",
    shape: "square",
    name: "Arcane Overload",
    description: "+10% burst spell damage and +6% spell critical chance.",
    tradeoff: "-4% DEF.",
    maxRank: 1,
    costPerRank: 3,
    requiredLevel: 9,
    requires: ["majo-sorcerer-starfall-surge"],
    position: { x: 25, y: 79 },
    effects: [
      { type: "burst_spell_damage", value: 10 },
      { type: "spell_crit_chance", value: 6 },
      { type: "defense_percent", value: -4 },
    ],
  },
  {
    id: "majo-healer-lifebloom-circle",
    tree: "majo",
    branch: "healer",
    shape: "square",
    name: "Lifebloom Circle",
    description: "+10% heal power and +6% party heal power.",
    tradeoff: "-3% ATK.",
    maxRank: 1,
    costPerRank: 3,
    requiredLevel: 9,
    requires: ["majo-healer-moonwell-grace"],
    position: { x: 75, y: 79 },
    effects: [
      { type: "heal_power", value: 10 },
      { type: "party_heal_power", value: 6 },
      { type: "attack_percent", value: -3 },
    ],
  },
  {
    id: "majo-core-ancient-channel",
    tree: "majo",
    branch: "merge",
    shape: "square",
    name: "Ancient Channel",
    description: "+6% MAGI and +6% mana efficiency.",
    tradeoff: null,
    maxRank: 1,
    costPerRank: 3,
    requiredLevel: 9,
    requires: ["majo-core-mana-loop"],
    position: { x: 50, y: 75 },
    effects: [
      { type: "magi_percent", value: 6 },
      { type: "mana_efficiency", value: 6 },
    ],
  },
  {
    id: "majo-capstone-grand-majo",
    tree: "majo",
    branch: "merge",
    shape: "triangle",
    name: "Grand Majo",
    description: "+10% MAGI, +10% heal power, +8% mana efficiency.",
    tradeoff: "-5% HP.",
    maxRank: 1,
    costPerRank: 4,
    requiredLevel: 10,
    requires: [
      "majo-sorcerer-arcane-overload",
      "majo-healer-lifebloom-circle",
      "majo-core-ancient-channel",
    ],
    position: { x: 50, y: 90 },
    effects: [
      { type: "magi_percent", value: 10 },
      { type: "heal_power", value: 10 },
      { type: "mana_efficiency", value: 8 },
      { type: "hp_percent", value: -5 },
    ],
  },
];
